### PR TITLE
add ruff linter,formatter

### PR DESCRIPTION
**Pull request by JMarkin**
### Checklist (adding a new tool):

- [x] If it's a linter it was exported in linter/init.lua
- [x] The tool was added to the README
- [x] I do not wish to write a test, but I can confirm that _it works on my machine_ _*OR*_ I have written corresponding tests for the tools I added. (don't worry if you didn't write a test, it's just nice to see the green check mark)

### CODE REVIEW

**Comment by xiaoshihou514** [comment]
Thanks for the pr! Looks mostly great, if you could kindly fix the tests accordingly I would merge this asap.

**Comment by JMarkin** [comment]
@xiaoshihou514 I don't understand why formatter ruff_fixed failed.
fname in tests works fine? On local machine it works
image

`ft("python"):fmt("ruff_fix") GuardFmt` works fine too.

**Comment by xiaoshihou514** [comment]
Well the truth is I don't know either.
You can see [this commit](https://github.com/nvimdev/guard-collection/commit/042420c9b49d94f65f039905629fabff93de95bf) and [this commit](https://github.com/nvimdev/guard-collection/commit/3c94a3fc630c0ebde3a674f8c714ec923d3e7c46) literally have no differences, but one ci run failed and the other succeded.
The tools are installed correctly and set up in the same manner, the tool version is the same, the test runs perfectly fine locally, but just fails on ci for no reason.
I don't know if it's some quirks with docker or neovim's io event scheduling, sadly I don't have the capabilities to fix this :(

**Comment by xiaoshihou514** [comment]
Hmm, now I looked more into this, I think it's because ruff exits with a non-zero exit code and emits stderr (like some linters do), so guard thought it failed, but in your screen shot there isn't one (in my case there's sth like `Found 1 error (1 fixed, 0 remaining).`)

**Pull request merged**
