### PR TITLE
feat: clippy-driver (rust)

### PR DESCRIPTION
**Pull request by LennyLizowzskiy**
### Checklist (adding a new tool):

- [x] If it's a linter it was exported in linter/init.lua
- [x] The tool was added to the README
- [ ] I do not wish to write a test, but I can confirm that _it works on my machine_ _*OR*_ I have written corresponding tests for the tools I added. (don't worry if you didn't write a test, it's just nice to see the green check mark)

## Need help with testing this
At first I forgot to change branches in my Neovim config, but now I fixed it and checked everything but there's no output from the plugin.

Example input:
```rust
use std::sync::Arc; // warn

fn main() {
    let x = 5; // warn

    100u8 << 10; // deny
}
```

Config:
```lua
local ft = require("guard.filetype")

ft("rust")
  :lint("clippy-driver")

require("guard").setup({
  fmt_on_save = false,
})
```

### CODE REVIEW

**Comment by LennyLizowzskiy** [comment]
TODO: In the final version `--edition=2021` should be removed. It's here now only for tests

**Comment by LennyLizowzskiy** [comment]
@xiaoshihou514 can you help, please?

**Comment by xiaoshihou514** [comment]
> @xiaoshihou514 can you help, please?

Sure, what's the problem?

**Comment by xiaoshihou514** [comment]
Hmm, unfourtunately I don't have a pc right now, here's what I would suggest :)
- run checkhealth to check neovim picks up the executable
- put vim.print and vim.notify inside the parse function to see stdout (maybe the linter is outputting stuff to stderr?)

**Comment by LennyLizowzskiy** [comment]
I checked and yes, linter is outputting stuff to stderr. Is there any way I can get this string in guard?

**Comment by xiaoshihou514** [comment]
Unfourtunately the stderr is not passed to the parse function right now. @glepnir seems to be busy contributing to neovim core :(

**Comment by LennyLizowzskiy** [comment]
Unfortunately, `clippy-driver`'s API is very minimal because it's meant to be used as `cargo clippy` that checks all files in the project altogether. There's no way I can manually forward the output to the stdout

**Comment by xiaoshihou514** [comment]
I see, in that case it's not possible to leverage clippy-driver with guard. Feel free to make prs to guard.nvim itself though! Some of the vim.uv code was tricky but you may want to give it a try.

**Comment by LennyLizowzskiy** [comment]
I'm not using Neovim anymore, so I won't be able to complete this PR.

I'm posting this formatter as plain text in case if I delete the PR branch (I'm not really sure if the changes I made will be saved otherwise in this case).
```lua
local lint = require('guard.lint')

local function trim(s)
  return s:gsub('^%s*(.-)%s*$', '%1')
end

return {
  cmd = 'clippy-driver',
  args = { '-', '--error-format=json', '--edition=2021' },
  stdin = true,
  parse = lint.from_json({
    get_diagnostics = function(result, bufnr)
      if result == '' then
        return {}
      end
      local res = '{' .. result:gsub('({[^\n]+})\n', '%1,\n') .. '}'
      return vim.json.decode(res)
    end,
    attributes = {
      lnum = 'spans.line_start',
      end_lnum = 'spans.line_end',
      code = function(json)
        -- concat all 'spans.text[n].text'
        local str = ''
        for k, v in pairs(json.spans.text) do
          str = str .. trim(v.text)
          if k ~= #json.spans.text then -- add " | " if current iteration is not last
            str = str .. ' | '
          end
        end
        return str
      end,
      col = 'spans.column_start',
      end_col = 'spans.column_end',
      severity = 'level',
      message = 'message',
    },
    severities = {
      lint.severities.info,
      lint.severities.warning,
      lint.severities.error,
    },
  }),
}

```

**Pull request closed without merging**
