### PR TITLE
feat: add npm-groovy-lint, jq, yamlfmt, yamlfix, xmllint formatters

### PR DESCRIPTION
**Pull request by 231tr0n**
### Checklist (adding a new tool):

- [x] If it's a linter it was exported in linter/init.lua
- [x] The tool was added to the README
- [x] I do not wish to write a test, but I can confirm that _it works on my machine_ _*OR*_ I have written corresponding tests for the tools I added. (don't worry if you didn't write a test, it's just nice to see the green check mark)

This PR also closes https://github.com/nvimdev/guard-collection/issues/38

### CODE REVIEW

**Comment by xiaoshihou514** [comment]
I am not sure about the jq config, shouldn't `jq .` do the trick?

**Comment by 231tr0n** [comment]
@xiaoshihou514 I actually tested it and it works. You can do it like this as well ``cat somefile.json | jq -M``.

**Comment by xiaoshihou514** [comment]
Yes, but do we really need this flag

**Comment by 231tr0n** [comment]
> Yes, but do we really need this flag

It outputs colors without it. So we might end up having terminal escape characters for colors afaik.

**Comment by xiaoshihou514** [comment]
By default, jq outputs colored JSON if writing to a terminal. _You can force it to produce color even if writing to a pipe or a file using -C_

**Comment by 231tr0n** [comment]
Ohh it works like that is it, ok then should i remove the -M flag then?

**Comment by xiaoshihou514** [comment]
I have no experience with other tools, so they look good to me.

**Comment by xiaoshihou514** [comment]
> Ohh it works like that is it, ok then should i remove the -M flag then?

Yes

**Comment by 231tr0n** [comment]
@xiaoshihou514! done removed it.

**Comment by xiaoshihou514** [comment]
Thanks for the pr btw :)

**Pull request merged**
