### PR TITLE
fix: test

### PR DESCRIPTION
**Pull request by xiaoshihou514**
ruff and golangci-lint not working right now, others _should_ work

### CODE REVIEW

**Comment by barrett-ruth** [comment]
thanks! bunch of path bs. How did you figure it out?

**Comment by xiaoshihou514** [comment]
> thanks! bunch of path bs. How did you figure it out?

A bunch of `which` and echos lol, and maybe some patience.
act was super nice tho, probably halfen the debug time and the terminal is just so much more asthetic than the webui

**Comment by barrett-ruth** [comment]
Ok awesome. any insight into why ruff and golangci-lint don't work despite being able to debug with act?

**Comment by xiaoshihou514** [comment]
Oh ktlint also doesn't work anymore. The linters returned an empty table so I'm guessing either the test or the config is not correct. Formatters kinda the same story. Not an installation issue, they passed the executable assertion. I will try to tweak the tests tomorrow to see if that helps.

**Comment by barrett-ruth** [comment]
Ok, make sure to watch out for things getting sent to stdout vs stderr

**Comment by xiaoshihou514** [comment]
`ruff --fix` has the same issue as prettierd, others are unclear

**Pull request merged**
