### PR TITLE
feat: automate linter exports

### PR DESCRIPTION
**Pull request by barrett-ruth**
automate linter exports. slightly finnicky solution but should work... may be better functions or ways to accomplish the task.

### CODE REVIEW

**Comment by barrett-ruth** [comment]
@xiaoshihou514 it looks like the clang tidy diagnostic test here failed. This is because you're trying to compare namespace fields of clang-tidy's diagnostic output:

image

with a guard namespace in the code [here](https://github.com/nvimdev/guard-collection/blob/ee07b4133ff362c52c4f8aaaf6b16c5ba7989252/test/linter/clang-tidy_spec.lua#L4), instead of the actual diagnostic namespace.

Currently, the namespace has no relevant info to diagnostics and is thus not capture as part of the diagnostic in the [clang-tidy linter code](https://github.com/nvimdev/guard-collection/blob/ee07b4133ff362c52c4f8aaaf6b16c5ba7989252/lua/guard-collection/linter/clang-tidy.lua#L9).

Solution:
1. You (or I) could add it to the regex to satisfy the test, even though the field would just be ignored.
2. I just delete [this line](https://github.com/nvimdev/guard-collection/blob/ee07b4133ff362c52c4f8aaaf6b16c5ba7989252/test/linter/clang-tidy_spec.lua#L27) in this commit and we're good.

**Comment by xiaoshihou514** [comment]
> Currently, the namespace has no relevant info to diagnostics and is thus not capture as part of the diagnostic in the clang-tidy linter code.

That's a neovim namespace used to "tag" stuff. `clang-tidy` uses `from_regex` which uses `diag_fmt` so its namespace _should_ be the Guard namespace. Dunno what happened, will investigate further.

**Comment by barrett-ruth** [comment]
The namespace may not be initialized before the test is run, so the field doesn't show up (nil).

**Comment by xiaoshihou514** [comment]
> The namespace may not be initialized before the test is run, so the field doesn't show up (nil).

That seems indeed valid, need to put all namespace evaluation after diagnostics is returned. That and some cleanup then tests should be passing fine.

**Comment by xiaoshihou514** [comment]
Actually, splitting up the formatter config does the same thing. Perhaps that is the better solution.

**Comment by xiaoshihou514** [comment]
@glepnir 's opinion is just to add an if to guard itself so we don't have to export this. Which does kind of make sense🤔

**Comment by xiaoshihou514** [comment]
> The namespace may not be initialized before the test is run, so the field doesn't show up (nil).

Will change that after this batch of pr gets merged.

**Pull request closed without merging**
